//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaApp.data.EntityS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CinemaPlace
    {
        public int id_Session { get; set; }
        public int Row { get; set; }
        public int Place { get; set; }
        public int Num_Ticket { get; set; }
        public int id_Ticket { get; set; }
        public int id_Hall { get; set; }
        public decimal Price_Film { get; set; }
    }
}
