//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaApp.data.EntityS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Get_All_Session
    {
        public int Session_id_Session { get; set; }
        public decimal Session_Price_Film { get; set; }
        public System.DateTime Session_Date_Film { get; set; }
        public Nullable<int> Session_Purchased_Tickets { get; set; }
        public int Session_id_Cinema { get; set; }
        public int Session_id_Hall { get; set; }
        public int Session_id_Film { get; set; }
        public int Hall_Row { get; set; }
        public int Hall_Number_Seats { get; set; }
        public string Inf_Cinema_Cinema_Description { get; set; }
        public string Inf_Cinema_Cinema_Adress { get; set; }
        public string Inf_Cinema_Cinema_Phone { get; set; }
        public string Film_Name_Film { get; set; }
        public string Film_Description { get; set; }
        public string Film_Actors { get; set; }
        public string Film_Genre { get; set; }
        public Nullable<System.TimeSpan> Film_Duration { get; set; }
        public byte[] Film_Image { get; set; }
    }
}
