//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaApp.data.EntityS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Session()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int id_Session { get; set; }
        public int id_Hall { get; set; }
        public int id_Film { get; set; }
        public decimal Price_Film { get; set; }
        public System.DateTime Date_Film { get; set; }
        public Nullable<int> Purchased_Tickets { get; set; }
        public int id_Cinema { get; set; }
        public bool is_Deleted { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Hall Hall { get; set; }
        public virtual Inf_Cinema Inf_Cinema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
