//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaApp.data.EntityS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int id_Ticket { get; set; }
        public int Num_Ticket { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public int id_Session { get; set; }
        public decimal Price_Ticket { get; set; }
        public int Row { get; set; }
        public int Place { get; set; }
        public string Session { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual Session Session1 { get; set; }
    }
}
